---
title: "TME-Pisaura"
output: html_document
editor_options:
  chunk_output_type: console
---


## Packages

```{r packages}
require(ggplot2)
require(ggpubr)
require(data.table)
require(rstatix)
require(tidyverse)
require(ggpubr)
require(lme4)
require(lmerTest)
require(ez)
require(mvnormtest)
require(psych)
require(moments)
```

## Harvest data

```{r data-harvest}
#read table
TME = fread("TME_Pisaura_data.csv", header = TRUE, encoding = 'Latin-1', stringsAsFactors = FALSE)
Etho1 = fread('Pisaura Ethovision 1.csv', header =TRUE, encoding = 'Latin-1', stringsAsFactors = FALSE)
Etho2 = fread('Pisaura Ethovision 2.csv', header =TRUE, encoding = 'Latin-1', stringsAsFactors = FALSE)
Etho3 = fread('Pisaura Ethovision 3.csv', header =TRUE, encoding = 'Latin-1', stringsAsFactors = FALSE)
Etho4 = fread('Pisaura Ethovision 4.csv', header =TRUE, encoding = 'Latin-1', stringsAsFactors = FALSE)
```

## Prepare data

```{r data-preparation}
#TME is body data and manual Site Selection and Personality
TMEnoNA = na.omit(TME)
names(TME)[names(TME) == "t_on_start side"] <- "t_on_start_side"
names(TMEnoNA)[names(TMEnoNA) == "t_on_start side"] <- "t_on_start_side"
gsub('c', 'C', TME$side_start)
gsub('c', 'C', TMEnoNA$side_start)
TMEnoNA = TMEnoNA %>%
  convert_as_factor(family, id, Camera, round, side_start, side_opp., day_test)

#Ethovision data read in and gather
Etho4 <- select(Etho4, -'seconds blank',-'seconds cue')
names(Etho1) <- names(Etho4)
names(Etho2) <- names(Etho4)
names(Etho3) <- names(Etho4)
Etho <- rbind(Etho1, Etho2, Etho3, Etho4) %>%
  na.omit() %>%
  filter(Mobile!='-')%>%
  as.data.table()
varnms <- names(Etho[,15:26])
Etho[ , (varnms) := lapply(.SD, function(x) gsub(',', '.', x)), .SDcol = varnms ]
Etho[, (varnms) := lapply(.SD, as.numeric), .SDcols= varnms]
Etho <- na.omit(Etho)
Etho[, (varnms) := lapply(.SD, function(x) round(x, digits = 3)), .SDcols= varnms]
#
#Etho and TME merge to data.frame 'dt'
#TODO: maybe better to only keep important columns (Movement related) in Etho data before merge

unique(TME$id) %in% unique(Etho$id) #check if IDs match, yes they do
#change day_test to week and both week columns to factor 
TME$week <- as.factor(TME$day_test)
Etho$week <- as.factor(as.integer(Etho$week))
#merge the tables by id and week
dt <- left_join(TME, Etho, by=c('id','week'))

#change column names blank spaces to underscores
names(dt) <- gsub(' ', '_', names(dt))
names(dt) <- gsub('__', '_', names(dt))

# TODO: change observations
#maybe #TODO:  sort out values where Ethovision data does not fit to manual data?
#maybe #TODO:  sort out unreasonable values of velocity
unique(dt$Zone)
dt <- dt %>%
  mutate(Zone <- case_when(Zone == 'In cue' ~ 'cue',
                           Zone == 'In blank' ~ 'blank')) #%>%
  # filter(Velocity_Mean<100) %>%
  #this deletes 9 observations
  # filter((Zone=='blank' & In_blank_s < 1.2*t_on_C) | (Zone=='cue' & In_cue_s < 1.2*t_on_B))
  #this deletes 2400 observations

#
#long format with only important columns
#
#TODO: here select all variables included in long format:
vars <- c('boldness','activity','t_on_C','t_on_B','Highly_mobile','Immobile','Mobile','Mobility_Mean_%')
#change all selected variables to one format (double or integer)
dt[,(vars) := lapply(.SD, function(x) as.numeric(x)), .SDcols = vars ]

dtl <- dt %>%
  #only the selected variables
  select(id, week, vars) %>%
  #to long format, identifying by id and week
  melt(id.vars = c('id','week'), measure.vars=vars) %>%
  #remove duplicates
  distinct() %>%
  #order by id
  arrange(id)
```

## Manipulate data

```{r adjust skewness}
#adjust skewness
skewness(TMEnoNA$boldness)
ggdensity(TMEnoNA, x = "boldness", fill = "lightgray", title = "boldness") +
  scale_x_continuous(limits = c(0, 600)) +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
skewness(TMEnoNA$activity)
ggdensity(TMEnoNA, x = "activity", fill = "lightgray", title = "activity") +
  scale_x_continuous(limits = c(0, 600)) +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
#boldness is negatively skewed --> mode > median > mean
#activity is positively skewed
TMEnoNA <- TMEnoNA %>%
  mutate(nombold=log10(max(boldness+1) - boldness),
         nomact=sqrt(activity))
TMEnoNA <- TMEnoNA[,lapply(TMEnoNA, function(x) x[is.finite(x)])]
shapiro.test(TMEnoNA$nombold)
skewness(TMEnoNA$nombold)
ggqqplot(TMEnoNA$nombold) 
ggdensity(TMEnoNA, x = "nombold", fill = "lightgray", title = "nombold") +
  scale_x_continuous(limits = c(0, 2.8)) +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
shapiro.test(TMEnoNA$nomact)
ks.test(TMEnoNA)
skewness(TMEnoNA$nomact)
ggqqplot(TMEnoNA$nomact)
ggdensity(TMEnoNA, x = "nomact", fill = "lightgray", title = "nomact") +
  scale_x_continuous(limits = c(0, 8)) +
  stat_overlay_normal_density(color = "red", linetype = "dashed")
```

```{r H1-testing}
## BOLDNESS AND ACTIVITY
#H1: Boldness and activity relate.

#
# FIRST WITH non-adjusted activity and boldness
#

#shapiro test
# significant difference from normally distribution when p<0,05
shapiro.test(TMEnoNA$activity)
ggqqplot(TMEnoNA$activity)
shapiro.test(TMEnoNA$boldness)
ggqqplot(TMEnoNA$boldness)
#no normal distribution for activity or boldness given
#pearson correlation senseless when not normally distributed --> kendall
cor.test(TMEnoNA$activity, TMEnoNA$boldness, method="kendall")
ggscatter(TMEnoNA, x = "activity", y = "boldness",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Activity", ylab = "boldness-score")
ggscatter(TMEnoNA, x = "activity", y = "boldness",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "kendall",
          xlab = "Activity", ylab = "boldness-score")
#GAM Modelling for better fit
ggplot(TMEnoNA,aes(activity,boldness))+
  geom_point()+
  geom_smooth(method='gam')
summary(mgcv::gam(TMEnoNA$boldness~s(TMEnoNA$activity, bs = "cs")))
#for each day_test so individuals appear only once at approx same age
day1 = filter(TMEnoNA,day_test==1)
ggplot(day1,aes(activity,boldness))+
  geom_point()+
  geom_smooth(method='gam')
summary(mgcv::gam(day1$boldness~s(day1$activity, bs = "cs")))
day2 = filter(TMEnoNA,day_test==2)
ggplot(day2,aes(activity,boldness))+
  geom_point()+
  geom_smooth(method='gam')
summary(mgcv::gam(day2$boldness~s(day2$activity, bs = "cs")))
day3 = filter(TMEnoNA,day_test==3)
  geom_point()+
ggplot(day3,aes(activity,boldness))+
  geom_smooth(method='gam')
summary(mgcv::gam(day3$boldness~s(day3$activity, bs = "cs")))

#
# SAME WITH skew-adjusted activity and boldness
#

cor.test(TMEnoNA$activity, TMEnoNA$boldness, method="pearson")
ggplot(TMEnoNA,aes(activity,boldness))+
  geom_point()+
  geom_smooth(method='gam')
summary(mgcv::gam(TMEnoNA$boldness~s(TMEnoNA$activity, bs = "cs")))

# do individuals keep their values the same in repeated measures
# day_test as moderator variable and check if moderator variable has no effect --> then the activity and boldness stayed the same for individuals
# or repeated-measures ANOVA?
```

```{r H2-testing}
#H2: test if there is a significant difference between our tonCeffect compared to a normally distribution with mean of 1 (and maybe sd of our tonCeffect)

TMEnoNA <- TMEnoNA %>%
  mutate(tonCeffect = t_on_C/300)
day1 <- TMEnoNA %>%
  filter(day_test == 1)
day2 <- TMEnoNA %>%
  filter(day_test == 2)
day3 <- TMEnoNA %>%
  filter(day_test ==3)

summary(day1$tonCeffect)
summary(day2$tonCeffect)
summary(day3$tonCeffect)

#T.Test : is
t.test(TMEnoNA$t_on_C, mu=300)
t.test(day1$t_on_C, mu=300)
#day 1 --> p<0,05
t.test(day2$t_on_C, mu=300)
t.test(day3$t_on_C, mu=300)

```

```{r H3-testing}
#H3:
res.man <- manova(cbind(activity, boldness)~tonCeffect,data=TMEnoNA)
summary.aov(res.man)
res.man1 <- manova(cbind(activity, boldness)~tonCeffect,data=day1)
summary.aov(res.man1)
res.man2 <- manova(cbind(activity, boldness)~tonCeffect,data=day2)
summary.aov(res.man2)
res.man3 <- manova(cbind(activity, boldness)~tonCeffect,data=day3)
summary.aov(res.man3)
TMEmean <- TMEnoNA %>%
  group_by(id) %>%
  summarize(tonCeffect = mean(tonCeffect),
            boldness = mean(boldness),
            activity = mean(activity))
res.man4 <- manova(cbind(activity, boldness)~tonCeffect,data=TMEmean)
summary.aov(res.man4)

#chisq makes no sense because no discrete variable
chisq.test(TMEmean$activity, TMEmean$tonCeffect)
chisq.test(TMEmean$boldness, TMEmean$tonCeffect)

```

```{r H4-testing}
#H4 do spiders of same heritage show similiar scores in activity boldness or tonCeffect

#MANOVA: does family have an effect on the variance of activity, boldness or tonCeffect?
res.man_H4 <- manova(cbind(activity,boldness,tonCeffect)~family, TMEnoNA)
summary.aov(res.man_H4)
#there is an significant effect on the variance of activity between family groups
```

```{r excluded}
# #TODO H: An individual shows similar activity and boldness scores over various observations.
# #         This indicates personality if other factors like age etc play no significant role.
# #         DONT KNOW ANY OTHER STATISTICAL TEST FOR PERSONALITY
#
#TODO H: Families share similar boldness and activity scores.
# ggboxplot(TMEnoNA$boldness) + ylab('boldness-score') + xlab('')
# ggplot(data=TMEnoNA, aes(x=day_test, y=boldness))+
#   geom_point(aes(color=family)) +
#   geom_line(aes(group=id,color=family))
#
# ## SITE SELECTION
# #TODO H: Activity in Personality test is different to activity in Site-Selection test
# #         This indicates that the application of Cue in the Testarena affects the spiders behaviour.
#
# #TODO H: The time spend on side with cue is dependent on the age of a spider (cricket boldness ontogeny Niemelä 2011).
# #         Compare to boldness as function of age.
# #         Data must be filtered for spiders that showed some activity / willingly chose a side
# #         when spiders have personality other factors like age should not play a significant role in behaviour control
# TMEmoved = TMEnoNA %>%
#   filter(t_on_C != 0) %>%
#   filter(t_on_C != 600)
# TMEmoved2 = TMEnoNA %>%
#   filter(activity != 0)
# TMEmoved3 = TMEmoved %>%
#   filter(activity != 0)
# ggplot(data=TMEnoNA, aes(x=day_test, y=t_on_C))+
#   geom_jitter(colour='grey70',position=position_jitter(0.03))+
#   geom_line(aes(group=id),colour='grey70')+
#   geom_boxplot(outlier.colour='black', outlier.shape=16, alpha=0.5) +
#   stat_compare_means(comparisons=list(c(1,2),c(2,3),c(1,3)),method='t.test', label='p.signif') +
#   theme_bw()
# ggplot(data=TMEmoved, aes(x=day_test, y=t_on_C))+
#   geom_point(colour='grey70')+
#   geom_line(aes(group=id),colour='grey70')+
#   geom_boxplot(outlier.colour='black', outlier.shape=16, alpha=0.5) +
#   stat_compare_means(comparisons=list(c(1,2),c(2,3),c(1,3)),method='t.test', label='p.signif') +
#   theme_bw()
# ggplot(data=TMEmoved2, aes(x=day_test, y=t_on_C))+
#   geom_point(colour='grey70')+
#   geom_line(aes(group=id),colour='grey70')+
#   geom_boxplot(outlier.colour='black', outlier.shape=16, alpha=0.5) +
#   stat_compare_means(comparisons=list(c(1,2),c(2,3),c(1,3)),method='t.test', label='p.signif') +
#   theme_bw()
# ggplot(data=TMEmoved3, aes(x=day_test, y=t_on_C))+
#   geom_point(colour='grey70')+
#   geom_line(aes(group=id),colour='grey70')+
#   geom_boxplot(outlier.colour='black', outlier.shape=16, alpha=0.5) +
#   stat_compare_means(comparisons=list(c(1,2),c(2,3),c(1,3)),method='t.test', label='p.signif') +
#   theme_bw()
#
# ggplot(data=TMEnoNA, aes(x=activity, y=t_on_start_side, group=id,color=id))+
#   geom_jitter(position=position_jitter(0.03))+
#   geom_line()+
#   theme_bw()
#
# # TODO H: activity and or boldness correlate to the time spent on the cue side, and or to the movement parameters
```